### ISSUE TITLE
Chrome warnings regarding the DOM are sent to the JS console after conducting a search in 'my-books'

### ISSUE THREAD

**Issue by lagunasmel** [flummoxing/BookSwap#130]
After a successful search on my-books is conducted, the following warnings regarding the DOM are posted to the JS console within Chrome itself:

![image](https://user-images.githubusercontent.com/30912739/100471360-1f23a200-30a8-11eb-8822-3d2b410e2eff.png)

I suspect these warnings are popping up because there are multiple input HTML elements that are generated on this page after conducting the search that get assigned the same ID.  As a general rule, HTML elements should not share the same ID. 

Note - to mimic this issue, open the JS console in chrome by right clicking on the page, select 'inspect' and look at the 'console' tab. Then, conduct a search on the page, such as 'harry potter.' These warnings pop up after that search is conducted.

**Comment by BenWichser** [comment]
These warnings all appear to be id naming collisions surrounding the `changePointsModal<suffix>` identifiers.  

This issue appears to be due to the fact that this modal was placed inside the table, creating an unused modal for each table row.  The collision would then occur due to the repeated use of identical id numbers.  There was no functionality loss, as each of the modals were populated with identical information (that of the selected entry in `my-books`).  Nevertheless, this was unfortunate identifier collision and unnecessarily taxing on the browser.

The fix appears to be in moving the modal code to after the table.

Issue appears to be resolved now.
